// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject3
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// penjumlahan
        /// </summary>
        public void penjumlahan()
        {
            #region Variable Declarations
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem1Button = this.UIMyCalculatorv1Window.UIItem1Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(30, 13));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(34, 15));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(30, 19));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(26, 24));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(34, 17));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(37, 5));
        }
        
        /// <summary>
        /// pengurangan
        /// </summary>
        public void pengurangan()
        {
            #region Variable Declarations
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WpfButton uIItem1Button = this.UIMyCalculatorv1Window.UIItem1Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(22, 17));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(22, 17));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(18, 12));

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(28, 18));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(33, 10));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(28, 20));
        }
        
        #region Properties
        public UIMyCalculatorv1Window UIMyCalculatorv1Window
        {
            get
            {
                if ((this.mUIMyCalculatorv1Window == null))
                {
                    this.mUIMyCalculatorv1Window = new UIMyCalculatorv1Window();
                }
                return this.mUIMyCalculatorv1Window;
            }
        }
        #endregion
        
        #region Fields
        private UIMyCalculatorv1Window mUIMyCalculatorv1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMyCalculatorv1Window : WpfWindow
    {
        
        public UIMyCalculatorv1Window()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MyCalculator v1";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyCalculator v1");
            #endregion
        }
        
        #region Properties
        public WpfButton UIDelButton
        {
            get
            {
                if ((this.mUIDelButton == null))
                {
                    this.mUIDelButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDelButton.SearchProperties[WpfButton.PropertyNames.Name] = "Del";
                    this.mUIDelButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIDelButton;
            }
        }
        
        public WpfButton UIItem1Button
        {
            get
            {
                if ((this.mUIItem1Button == null))
                {
                    this.mUIItem1Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem1Button.SearchProperties[WpfButton.PropertyNames.Name] = "1";
                    this.mUIItem1Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem1Button;
            }
        }
        
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WpfButton.PropertyNames.Name] = "+";
                    this.mUIItemButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfButton UIItem2Button
        {
            get
            {
                if ((this.mUIItem2Button == null))
                {
                    this.mUIItem2Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem2Button.SearchProperties[WpfButton.PropertyNames.Name] = "2";
                    this.mUIItem2Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem2Button;
            }
        }
        
        public WpfButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WpfButton.PropertyNames.Name] = "=";
                    this.mUIItemButton1.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WpfButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WpfButton.PropertyNames.Name] = "-";
                    this.mUIItemButton2.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIDelButton;
        
        private WpfButton mUIItem1Button;
        
        private WpfButton mUIItemButton;
        
        private WpfButton mUIItem2Button;
        
        private WpfButton mUIItemButton1;
        
        private WpfButton mUIItemButton2;
        #endregion
    }
}
